apiVersion: "v1"
kind: "Secret"
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    {{- include "labels" . | nindent 4 }}
type: "Opaque"
stringData:
  id: |
    {{- .Values.selfhosted_gire_private_key | nindent 4 }}
  trusted.pub: |
    {{- join "\n" .Values.selfhosted_gire_known_hosts | nindent 4 }}
  sources.yaml: |
    {{- .Values.selfhosted_gire_sources | toYaml | nindent 4 }}
