apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "{{ .Chart.Name }}-backups"
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  storageClassName: "app-data"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
