apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: "data"
          persistentVolumeClaim:
            claimName: "{{ .Chart.Name }}"
        - name: "cache"
          persistentVolumeClaim:
            claimName: "{{ .Chart.Name }}-cache"
      containers:
        - name: "{{ .Chart.Name }}-server"
          image: "ghcr.io/immich-app/immich-server:{{ .Chart.AppVersion }}"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: "IMMICH_PORT"
              value: "2283"
            - name: "DB_HOSTNAME"
              value: "localhost"
            - name: "DB_DATABASE_NAME"
              value: "immich"
            - name: "DB_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: "{{ .Chart.Name }}"
                  key: "pg-username"
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "{{ .Chart.Name }}"
                  key: "pg-password"
            - name: "REDIS_HOSTNAME"
              value: "localhost"
            - name: "IMMICH_MACHINE_LEARNING_URL"
              value: "http://localhost:3003"
          ports:
            - name: "http"
              containerPort: 2283
          volumeMounts:
            - name: "data"
              subPath: "gallery"
              mountPath: "/usr/src/app/upload"

        - name: "{{ .Chart.Name }}-machine-learning"
          image: "ghcr.io/immich-app/immich-machine-learning:{{ .Chart.AppVersion }}"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: "IMMICH_PORT"
              value: "3003"
          volumeMounts:
            - name: "cache"
              subPath: "ml-models"
              mountPath: "/cache"

        - name: "{{ .Chart.Name }}-redis"
          image: "redis:6.2.16-alpine"
          imagePullPolicy: "IfNotPresent"

        - name: "{{ .Chart.Name }}-database"
          image: "ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: "POSTGRES_DB"
              value: "immich"
            - name: "POSTGRES_USER"
              valueFrom:
                secretKeyRef:
                  name: "{{ .Chart.Name }}"
                  key: "pg-username"
            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "{{ .Chart.Name }}"
                  key: "pg-password"
            - name: "POSTGRES_INITDB_ARGS"
              value: "--data-checksums"
          volumeMounts:
            - name: "data"
              subPath: "postgres"
              mountPath: "/var/lib/postgresql/data"
