apiVersion: "v1"
kind: "Secret"
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    {{- include "labels" . | nindent 4 }}
type: "Opaque"
stringData:
  lidarr-token: "{{ .Values.selfhosted_lidarr_token }}"
  prowlarr-token: "{{ .Values.selfhosted_prowlarr_token }}"
  radarr-token: "{{ .Values.selfhosted_radarr_token }}"
  sonarr-token: "{{ .Values.selfhosted_sonarr_token }}"
