- name: "Configure Raspberry Pi"
  hosts: selfhosted

  vars_files:
    - "../defaults.yaml"
    - "../vars.yaml"

  tasks:
    - name: "Add required kernel parameters"
      loop:
        - "cgroup_memory=1"
        - "cgroup_enable=memory"
      ansible.builtin.replace:
        path: /boot/cmdline.txt
        regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
        replace: '\1 {{ item }}'

    - name: "Configure swap"
      block:
        - name: "Disable swap temporarily"
          ansible.builtin.command: dphys-swapfile swapoff
        - name: "Set the swap size"
          ansible.builtin.replace:
            path: /etc/dphys-swapfile
            regexp: "^CONF_SWAPSIZE=(\\d+)$"
            replace: "CONF_SWAPSIZE={{ selfhosted_swap_size }}"
        - name: "Re-initialize swapfile"
          ansible.builtin.command: dphys-swapfile setup
      always:
        - name: "Enable swap"
          ansible.builtin.command: dphys-swapfile swapon
