- name: "Configure Kubernetes cluster"
  hosts: selfhosted

  vars:
    required_addons:
      - dns
      - ingress
      - host-access
      - hostpath-storage
    cri_tools_filename: "crictl-v{{ selfhosted_cri_tools_version }}-linux-{{ os_arch_mapping[ansible_architecture] or ansible_architecture }}.tar.gz"

  vars_files:
    - "../defaults.yaml"
    - "../vars.yaml"

  tasks:
    - name: "Create storage directory for Kubernetes"
      ansible.builtin.file:
        path: /var/lib/kubernetes-storage
        state: directory

    - name: "Install snapd"
      ansible.builtin.package:
        name: snapd
        state: present

    - name: "Install microk8s"
      community.general.snap:
        name: microk8s
        state: present
        classic: true
    - name: "Check microk8s works"
      ansible.builtin.command: /snap/bin/microk8s status --wait-ready
      changed_when: false

    - name: "Install microk8s extensions"
      ansible.builtin.command: "/snap/bin/microk8s enable {{ required_addons | join(' ') }} "

    - name: "Download crictl"
      ansible.builtin.get_url:
        url: "https://github.com/kubernetes-sigs/cri-tools/releases/download/v{{ selfhosted_cri_tools_version }}/{{ cri_tools_filename }}"
        dest: "/tmp"
        checksum: "{{ selfhosted_cri_tools_checksum }}"
    - name: "Install crictl"
      ansible.builtin.unarchive:
        remote_src: true
        src: "/tmp/{{ cri_tools_filename }}"
        dest: /usr/local/bin
        include: ["crictl"]
        mode: "755"
        owner: root
        group: root
