- name: "Configure Kubernetes cluster"
  hosts: selfhosted

  vars:
    required_addons:
      - dns
      - ingress
      - host-access
      - hostpath-storage

  vars_files:
    - "../defaults.yaml"
    - "../vars.yaml"

  tasks:
    - name: "Create storage directory for Kubernetes"
      ansible.builtin.file:
        path: /var/lib/kubernetes-storage
        state: directory

    - name: "Install snapd"
      ansible.builtin.package:
        name: snapd
        state: present

    - name: "Install microk8s"
      community.general.snap:
        name: microk8s
        state: present
        classic: true
    - name: "Check microk8s works"
      ansible.builtin.command: /snap/bin/microk8s status --wait-ready
      changed_when: false

    - name: "Install microk8s extensions"
      ansible.builtin.command: "/snap/bin/microk8s enable {{ required_addons | join(' ') }} "
