- name: "Pull kubeconfig from the Kubernetes cluster"
  hosts: selfhosted

  vars_files:
    - "../defaults.yaml"
    - "../vars.yaml"

  tasks:
    - name: "Get remote kubeconfig contents"
      ansible.builtin.command: "/snap/bin/microk8s config"
      register: remote_kubeconfig_cmd
      changed_when: false

    - name: "Get local kubeconfig contents"
      delegate_to: localhost
      ansible.builtin.command: "kubectl config view --kubeconfig {{ local_kubeconfig_path }} --raw"
      register: local_kubeconfig_cmd
      changed_when: false

    - name: "Create temporary file for config merging"
      delegate_to: localhost
      ansible.builtin.tempfile: {}
      register: merge_file
      changed_when: false

    # TODO: find a way to generate proper certificates so this works `| replace('127.0.0.1', inventory_hostname))`
    - name: "Append remote kubeconfig to the local one"
      delegate_to: localhost
      ansible.builtin.copy:
        content: |
          {{ remote_kubeconfig_cmd.stdout }}
          ---
          {{ local_kubeconfig_cmd.stdout }}
        dest: "{{ merge_file.path }}"
      changed_when: false

    - name: "Merge kubeconfigs"
      delegate_to: localhost
      ansible.builtin.command: "kubectl config view --kubeconfig {{ merge_file.path }} --flatten"
      register: merged_kubeconfig_cmd
      changed_when: false

    - name: "Save merged kubeconfig"
      delegate_to: localhost
      ansible.builtin.copy:
        content: "{{ merged_kubeconfig_cmd.stdout }}"
        dest: "{{ local_kubeconfig_path }}"

    - name: Remove temporary file
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{ merge_file.path }}"
        state: absent
      changed_when: false
