apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: "data"
          persistentVolumeClaim:
            claimName: "{{ .Chart.Name }}"
      containers:
        - name: "{{ .Chart.Name }}"
          image: "ghcr.io/linuxserver/prowlarr:{{ .Chart.AppVersion }}"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: "PUID"
              value: "{{ .Values.selfhosted_users_for_apps.prowlarr.uid }}"
            - name: "UMASK"
              value: "002"
          ports:
            - name: "http"
              containerPort: 9696
          volumeMounts:
            - name: "data"
              mountPath: "/config"
