apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  replicas: 1
  strategy:
    type: "Recreate"
  template:
    metadata:
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: "data"
          persistentVolumeClaim:
            claimName: "{{ .Chart.Name }}"
        - name: "downloads"
          hostPath:
            path: "{{ .Values.selfhosted_storage_path }}/Downloads"
            type: "DirectoryOrCreate"
      initContainers:
        - name: "chown"
          image: "busybox"
          imagePullPolicy: "IfNotPresent"
          command: ["sh", "-c", "chown -R 1000:1000 /config"]
          volumeMounts:
            - name: "data"
              mountPath: "/config"
      containers:
        - name: "{{ .Chart.Name }}"
          image: "linuxserver/transmission:{{ .Chart.AppVersion }}"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: "USER"
              valueFrom:
                secretKeyRef:
                  name: "{{ .Chart.Name }}"
                  key: "username"
            - name: "PASS"
              valueFrom:
                secretKeyRef:
                  name: "{{ .Chart.Name }}"
                  key: "password"
            - name: "PUID"
              value: "1000"
            - name: "PGID"
              value: "1000"
          ports:
            - name: "http"
              containerPort: 9091
            - name: "peer-tcp"
              containerPort: 51413
              hostPort: 51413
              protocol: "TCP"
            - name: "peer-udp"
              containerPort: 51413
              hostPort: 51413
              protocol: "UDP"
          volumeMounts:
            - name: "data"
              mountPath: "/config"
            - name: "downloads"
              mountPath: "/downloads"
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
