apiVersion: "v1"
kind: "Secret"
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    {{- include "labels" . | nindent 4 }}
type: "Opaque"
stringData:
  username: "{{ .Values.selfhosted_grafana_username }}"
  password: "{{ .Values.selfhosted_grafana_password }}"

  vm-username: "{{ .Values.selfhosted_victoriametrics_username }}"
  vm-password: "{{ .Values.selfhosted_victoriametrics_password }}"
