apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  promtail.yaml: |-
    {{- .Files.Get "resources/promtail.yaml" | nindent 4 }}
