apiVersion: "apps/v1"
kind: "DaemonSet"
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: "logs"
          hostPath:
            path: "/var/log/pods"
        - name: "state"
          hostPath:
            path: "/run/promtail"
        - name: "config"
          configMap:
            name: "{{ .Chart.Name }}"
      containers:
        - name: "{{ .Chart.Name }}"
          image: "grafana/promtail:{{ .Chart.AppVersion }}"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: "HOSTNAME"
              valueFrom:
                fieldRef:
                  fieldPath: "spec.nodeName"
          args:
            - "-config.file=/etc/promtail/promtail.yaml"
          volumeMounts:
            - name: "logs"
              mountPath: "/var/log/pods"
              readOnly: true
            - name: "state"
              mountPath: "/run/promtail"
            - name: "config"
              mountPath: "/etc/promtail"
