{
 "title": "VPN",
 "templating": {
  "list": [
   { "name": "vpn_server", "query": { "query": "label_values(vpn_server)" } },
   { "name": "user_name", "query": { "query": "label_values(user_name)" } },
   { "name": "grouping" }
  ]
 },
 "panels": [
  {
   "title": "Total data by user",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "running_sum(sum(increase(wireguard_received_bytes_total{vpn_server=\"$vpn_server\"}), increase(wireguard_sent_bytes_total{vpn_server=\"$vpn_server\"}), increase(xray_received_bytes_total{vpn_server=\"$vpn_server\"}), increase(xray_sent_bytes_total{vpn_server=\"$vpn_server\"})) by (user_name))"
    }
   ]
  },
  {
   "title": "Wireguard data total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "running_sum(sum(increase(wireguard_received_bytes_total{vpn_server=\"$vpn_server\",user_name=~\"$user_name\"}), increase(wireguard_sent_bytes_total{vpn_server=\"$vpn_server\",user_name=~\"$user_name\"})) by ($grouping))"
    }
   ]
  },
  {
   "title": "Xray data total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "running_sum(sum(increase(xray_received_bytes_total{vpn_server=\"$vpn_server\",user_name=~\"$user_name\"}), increase(xray_sent_bytes_total{vpn_server=\"$vpn_server\",user_name=~\"$user_name\"})) by ($grouping))"
    }
   ]
  }
 ]
}