{
 "title": "Node exporter",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "w": 12, "h": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{job=\"$job\",instance=\"$instance\",mode!=\"idle\"}[$__rate_interval])) / count(count(node_cpu_seconds_total{job=\"$job\",instance=\"$instance\"}) by (cpu))",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "RAM/Swap usage",
   "type": "timeseries",
   "gridPos": { "w": 12, "h": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$job\",instance=\"$instance\"} - node_memory_MemFree_bytes{job=\"$job\",instance=\"$instance\"} - node_memory_Cached_bytes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "RAM usage"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "RAM cache usage"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"$job\",instance=\"$instance\"} - node_memory_SwapFree_bytes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Swap usage"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$job\",instance=\"$instance\"} + node_memory_SwapTotal_bytes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Total memory"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "w": 12, "h": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{type}} {{zone}}"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "bargauge",
   "gridPos": { "w": 12, "h": 8, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job=\"$job\",instance=\"$instance\",fstype!=\"tmpfs\",mountpoint!~\"/var/snap/.*\"} - node_filesystem_free_bytes{job=\"$job\",instance=\"$instance\",fstype!=\"tmpfs\",mountpoint!~\"/var/snap/.*\"}) / node_filesystem_size_bytes{job=\"$job\",instance=\"$instance\",fstype!=\"tmpfs\",mountpoint!~\"/var/snap/.*\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Total inbound/outbound traffic",
   "type": "timeseries",
   "gridPos": { "w": 24, "h": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "running_sum(sum(increase(node_network_receive_bytes_total{job=\"$job\",instance=\"$instance\",device!~\".*cali.*\",device!~\"wg\\\\d+\",device!=\"lo\"})))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "running_sum(sum(increase(node_network_transmit_bytes_total{job=\"$job\",instance=\"$instance\",device!~\".*cali.*\",device!~\"wg\\\\d+\",device!=\"lo\"})))",
     "legendFormat": "Outbound"
    }
   ]
  }
 ]
}