apiVersion: "v1"
kind: "Service"
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
  type: "ClusterIP"
  ports:
    - name: "http"
      port: 80
      targetPort: "http"
