apiVersion: 1
datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    uid: victoria-metrics
    url: http://victoria-metrics
    editable: false
    isDefault: true
    basicAuth: true
    basicAuthUser: $VM_USERNAME
    secureJsonData:
      basicAuthPassword: $VM_PASSWORD
