- name: "Map architecture name"
  ansible.builtin.set_fact:
    node_exporter_arch: "{{ node_exporter_arch_mapping[ansible_architecture] }}"
- name: "Calculate artifact name"
  ansible.builtin.set_fact:
    node_exporter_artifact_name: "node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}"

- name: "Cleanup"
  ansible.builtin.include_tasks:
    file: "0_cleanup.yaml"

- name: "Download node-exporter"
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/{{ node_exporter_artifact_name }}.tar.gz"
    checksum: "{{ node_exporter_checksum[node_exporter_arch] }}"
    dest: "/tmp/node-exporter-{{ node_exporter_version }}.tar.gz"

- name: "Unpack node-exporter binary"
  ansible.builtin.unarchive:
    remote_src: true
    src: "/tmp/node-exporter-{{ node_exporter_version }}.tar.gz"
    dest: "/usr/local/bin"
    include: "{{ node_exporter_artifact_name }}/node_exporter"
    mode: "755"
    extra_opts: "--strip-components=1"

- name: "Copy node-exporter.service"
  ansible.builtin.copy:
    src: "node-exporter.service"
    dest: "/usr/lib/systemd/system/node-exporter.service"

- name: "Enable and start node-exporter.service"
  ansible.builtin.systemd:
    name: "node-exporter"
    state: "restarted"
    enabled: true
    daemon-reload: true
