apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deluge
spec:
  rules:
    - host: "deluge.{{ selfhosted_hostname }}"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: deluge
                port:
                  number: 80

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge
spec:
  storageClassName: app-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deluge
spec:
  selector:
    matchLabels:
      app: deluge
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: deluge
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: deluge
        - name: downloads
          hostPath:
            path: "{{ selfhosted_storage_path }}/Media/Downloads"
            type: DirectoryOrCreate
      initContainers:
        - name: chown
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "chown -R 1000:1000 /config"]
          volumeMounts:
            - name: data
              mountPath: /config
      containers:
        - name: deluge
          image: ghcr.io/linuxserver/deluge:2.1.1
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - containerPort: 8112
            - containerPort: 6881
              hostPort: 6881
              protocol: TCP
            - containerPort: 6881
              hostPort: 6881
              protocol: UDP
          volumeMounts:
            - name: data
              mountPath: /config
            - name: downloads
              mountPath: /downloads
          resources:
            limits:
              memory: 512Mi # wtf is this memory usage

---

apiVersion: v1
kind: Service
metadata:
  name: deluge
spec:
  selector:
    app: deluge
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8112
