apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gire
spec:
  storageClassName: app-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gire
spec:
  selector:
    matchLabels:
      app: gire
  replicas: 1
  template:
    metadata:
      labels:
        app: gire
    spec:
      volumes:
        - name: chown
          emptyDir: {}
        - name: config
          secret:
            secretName: gire
        - name: data
          persistentVolumeClaim:
            claimName: gire
      initContainers:
        - name: chown
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "cp /id /chown/id && chown 1001:1001 /chown/id"]
          volumeMounts:
            - name: chown
              mountPath: /chown
            - name: config
              subPath: id
              mountPath: /id
      containers:
        - name: gire
          image: sibwaf/gire:latest
          imagePullPolicy: Never
          env:
            - name: GIRE_CRON
              value: "0 */15 * * * *"
          ports:
            - containerPort: 22
          volumeMounts:
            - name: chown
              subPath: id
              mountPath: /keys/id
            - name: config
              subPath: trusted.pub
              mountPath: /keys/trusted/trusted.pub
            - name: config
              subPath: sources.yaml
              mountPath: /app/sources.yaml
            - name: data
              mountPath: /app/repositories
          resources:
            limits:
              memory: 64Mi
