apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lidarr
spec:
  rules:
    - host: "lidarr.{{ selfhosted_hostname }}"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: lidarr
                port:
                  number: 80
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr
spec:
  storageClassName: app-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
spec:
  selector:
    matchLabels:
      app: lidarr
  replicas: 1
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: lidarr
        - name: library
          hostPath:
            path: "{{ selfhosted_storage_path }}/Media"
            type: DirectoryOrCreate
      containers:
        - name: lidarr
          image: ghcr.io/linuxserver/lidarr:1.1.4-develop
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8686
          volumeMounts:
            - name: data
              mountPath: /config
            - name: library
              mountPath: /library

---

apiVersion: v1
kind: Service
metadata:
  name: lidarr
spec:
  selector:
    app: lidarr
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8686
