apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
spec:
  rules:
    - host: "prowlarr.{{ selfhosted_hostname }}"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: prowlarr
                port:
                  number: 80

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr
spec:
  storageClassName: app-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  selector:
    matchLabels:
      app: prowlarr
  replicas: 1
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: prowlarr
      containers:
        - name: prowlarr
          image: ghcr.io/linuxserver/prowlarr:1.8.5-develop
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9696
          volumeMounts:
            - name: data
              mountPath: /config

---

apiVersion: v1
kind: Service
metadata:
  name: prowlarr
spec:
  selector:
    app: prowlarr
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 9696
