apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
spec:
  rules:
    - host: "sonarr.{{ selfhosted_hostname }}"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: sonarr
                port:
                  number: 80

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr
spec:
  storageClassName: app-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  selector:
    matchLabels:
      app: sonarr
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sonarr
        - name: library
          hostPath:
            path: "{{ selfhosted_storage_path }}/Media"
            type: DirectoryOrCreate
        - name: downloads
          hostPath:
            path: "{{ selfhosted_seedbox_path }}/Transmission"
            type: Directory
      initContainers:
        - name: mkdir
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["mkdir", "-p", "/downloads/sonarr"]
      containers:
        - name: sonarr
          image: ghcr.io/linuxserver/sonarr:4.0.0-develop
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8989
          volumeMounts:
            - name: data
              mountPath: /config
            - name: library
              mountPath: /library
            - name: downloads
              mountPath: /downloads
              readOnly: true

---

apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  selector:
    app: sonarr
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8989
