apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: syncthing
spec:
  rules:
    - host: "syncthing.{{ selfhosted_hostname }}"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: syncthing
                port:
                  number: 80

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing
spec:
  storageClassName: app-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
spec:
  selector:
    matchLabels:
      app: syncthing
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: syncthing
        - name: storage
          hostPath:
            path: "{{ selfhosted_storage_path }}"
            type: Directory
      initContainers:
        - name: chown
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "if [ -d /var/syncthing/config ]; then chown -R 1000:1000 /var/syncthing/config; fi"]
          volumeMounts:
            - name: data
              mountPath: /var/syncthing
      containers:
        - name: syncthing
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          image: syncthing/syncthing:1.23.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8384
            - containerPort: 21027
              hostPort: 21027
              protocol: UDP
            - containerPort: 22000
              hostPort: 22000
              protocol: TCP
            - containerPort: 22000
              hostPort: 22000
              protocol: UDP
          volumeMounts:
            - name: data
              mountPath: /var/syncthing
            - name: storage
              mountPath: /storage

---

apiVersion: v1
kind: Service
metadata:
  name: syncthing
spec:
  selector:
    app: syncthing
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8384
