apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission
spec:
  rules:
    - host: "transmission.{{ selfhosted_hostname }}"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: transmission
                port:
                  number: 80

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission
spec:
  storageClassName: app-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
spec:
  selector:
    matchLabels:
      app: transmission
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: transmission
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: transmission
        - name: downloads
          hostPath:
            path: "{{ selfhosted_storage_path }}/Downloads"
            type: DirectoryOrCreate
      initContainers:
        - name: chown
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "chown -R 1000:1000 /config"]
          volumeMounts:
            - name: data
              mountPath: /config
      containers:
        - name: transmission
          image: linuxserver/transmission:4.0.3
          imagePullPolicy: IfNotPresent
          env:
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: transmission-credentials
                  key: username
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: transmission-credentials
                  key: password
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - containerPort: 9091
            - containerPort: 51413
              hostPort: 51413
              protocol: TCP
            - containerPort: 51413
              hostPort: 51413
              protocol: UDP
          volumeMounts:
            - name: data
              mountPath: /config
            - name: downloads
              mountPath: /downloads
          resources:
            limits:
              memory: 512Mi

---

apiVersion: v1
kind: Service
metadata:
  name: transmission
spec:
  selector:
    app: transmission
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 9091
